### ISSUE TITLE
Please check Search.php for syntax error

### ISSUE THREAD

**Issue by adamteller-macmillan** [marklogic/mlphp#11]
Hello MarkLogic, recently while using PHP Rest API code, I got an error involving the word 'collection' not being a defined constant.

https://github.com/marklogic/mlphp/blob/master/api/MarkLogic/MLPHP/Search.php

Line 340: `public function setCollection($collection)`

Line 342: `$this->collection = collection;`

should this really be: $this->collection = `$collection`;  ? (Dollar sign in front of word collection).

I changed it in my copy of the code and then the code functioned as expected.

**Comment by aebadirad** [comment]
Yes, you are correct. This was corrected in the dev branch where the current active development is taking place.
