### ISSUE TITLE
Incorrect Setting Of CURLOPT_HTTPHEADER In RESTClient

### ISSUE THREAD

**Issue by apeacock1991** [marklogic/mlphp#16]
In the RESTClient class there is:

        foreach ($headers as $key => $val) {
            curl_setopt($ch, CURLOPT_HTTPHEADER, array($key . ': ' . $val));
        }

This is incorrect, instead of passing in multiple arrays you have to pass onearray of values (http://php.net/manual/en/function.curl-setopt.php), for example I've tweaked it so that it works by doing the following:

    foreach ($headers as $key => $val) {
        $formattedHeaders[] = $key . ':' . $val;
    }

    curl_setopt($ch, CURLOPT_HTTPHEADER, $formattedHeaders);

**Comment by wooldridge** [comment]
Thanks for catching this bug! Fixed by:

https://github.com/marklogic/mlphp/pull/18
